pipeline fix

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -19,12 +19,20 @@ jobs:
         with:
           terraform_version: "1.4.0"  # Use your desired Terraform version
 
-      # Install AWS CLI
-      - name: Install AWS CLI
+      # Install or Update AWS CLI
+      - name: Install or Update AWS CLI
         run: |
-          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
-          unzip awscliv2.zip
-          sudo ./aws/install
+          # Check if AWS CLI is installed, and update if necessary
+          if ! command -v aws &> /dev/null
+          then
+            echo "AWS CLI not found, installing..."
+            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
+            unzip awscliv2.zip
+            sudo ./aws/install
+          else
+            echo "AWS CLI found, updating..."
+            sudo aws/install --update
+          fi
 
       # Configure AWS credentials (set these in GitHub Secrets)
       - name: Configure AWS credentials
